apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: crew-ai-test25102303
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/crew-ai-test25102303:8c8e73257a7a3feed48490223e8b8831e73f9dae@sha256:340c08f885da8f879023a73312b3df56b6948bb1db2a2c57a2b68f4e6c2ba717 # use pre-built to bootstrap
          name: app-inference
